In [2]:
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import Dataset
import torch
import json

# Custom Dataset
class ClaimClassificationDataset(Dataset):
    def __init__(self, data_path, tokenizer, max_len=512):
        self.data = self.load_data(data_path)
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.label_map = {'SUPPORTS': 0, 'REFUTES': 1, 'NOT_ENOUGH_INFO': 2, 'DISPUTED': 3}

    def load_data(self, data_path):
        """Load and preprocess data from JSON."""
        with open(data_path, "r") as f:
            data = json.load(f)
        return data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        claim = "CLAIM:" + item['claim_text']
        evidence = " [SEP] EVIDENCE:".join(item['evidences'])
        #claim = item['claim_text']
        #evidence = " [SEP] ".join(item['evidences'])
        inputs = self.tokenizer(claim + evidence,
                                truncation=True, padding="max_length",  # Use dynamic padding
                                max_length=self.max_len, return_tensors='pt')
        inputs = {k: v.squeeze(0) for k, v in inputs.items()}
        inputs['labels'] = torch.tensor(self.label_map[item['claim_label']])
        return inputs

def create_dataloaders(train_path, dev_path, tokenizer, batch_size=16, max_len=512):
    """
    Creates training and validation data loaders.

    Args:
        train_path (str): Path to training data JSON file.
        dev_path (str): Path to development data JSON file.
        tokenizer (transformers.Tokenizer): BERT tokenizer.
        batch_size (int): Batch size for data loaders.
        max_len (int): Maximum length for tokenization.

    Returns:
        DataLoader: Training and validation data loaders.
    """
    train_dataset = ClaimClassificationDataset(train_path, tokenizer, max_len)
    dev_dataset = ClaimClassificationDataset(dev_path, tokenizer, max_len)

    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    dev_loader = torch.utils.data.DataLoader(dev_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, dev_loader

In [3]:
import torch
import torch.nn as nn
from torch.amp import GradScaler, autocast
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

# GradScaler
scaler = GradScaler()  

   
def train_one_epoch(model, train_loader, optimizer, scheduler, autocast_flag=False):
    model.train()
    total_loss = 0

    for batch in train_loader:
        # Move data to device
        # print(batch["input_ids"])
        input_ids = batch["input_ids"].to(DEVICE)
        attention_mask = batch["attention_mask"].to(DEVICE)
        labels = batch["labels"].to(DEVICE)

        # Zero gradients
        optimizer.zero_grad()

        # Forward pass
        if autocast_flag:
            with autocast(device_type='cuda'):  # Updated autocast
                outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
        else:
            outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss

         # Backward pass
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    return avg_loss


def evaluate(model, dev_loader):
    model.eval()
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in dev_loader:
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            labels = batch["labels"].to(DEVICE)

            outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            total_loss += loss.item()

            # Compute accuracy
            logits = outputs.logits
            _, preds = torch.max(logits, dim=1)
            correct_predictions += (preds == labels).sum().item()
            total_samples += labels.size(0)

            # Collect all predictions and labels for metrics calculation
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # Calculate average loss and accuracy
    avg_loss = total_loss / len(dev_loader)
    accuracy = correct_predictions / total_samples

    # Calculate precision, recall, and F1 score
    precision = precision_score(all_labels, all_preds, average='weighted', zero_division=0)
    recall = recall_score(all_labels, all_preds, average='weighted', zero_division=0)
    f1 = f1_score(all_labels, all_preds, average='weighted', zero_division=0)

    # Confusion matrix
    cm = confusion_matrix(all_labels, all_preds)
    print("Confusion Matrix:\n", cm)
    
    # Classification report for per-class recall
    # report = classification_report(all_labels, all_preds, zero_division=0)
    # print(report)

    # Return all metrics
    metrics = {
        "avg_loss": avg_loss,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1
    }

    return metrics

def train_model(model, train_loader, dev_loader, epochs, optimizer, scheduler, best_model_path, autocast_flag):
    best_accuracy = 0
    best_precision = 100

    print("START TRAINING: ")
    for epoch in range(epochs):
        print(f"----Epoch {epoch + 1}/{epochs}----")

        # Training
        train_loss = train_one_epoch(model, train_loader, optimizer, scheduler, autocast_flag)
        print(f"Training Loss: {train_loss:.4f}")

        # Evaluation
        val_metrics = evaluate(model, dev_loader)
        print(f"Validation Loss:", val_metrics)

        # Save the best model
        if val_metrics["accuracy"] > best_accuracy:
            best_accuracy = val_metrics["accuracy"]
            best_model = model
            #torch.save(best_model, "best_model.pt")
            #print("Model saved as 'best_model.pt'")

    best_model.to('cpu')
    torch.save(best_model.state_dict(), best_model_path)

In [5]:
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW
import time

# Define hyperparameters
BATCH_SIZE = 16
EPOCHS = 10
MAX_LEN = 512
LEARNING_RATE = 2e-5

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Paths
# TRAIN_PATH = "data/claim-evidence-set/train_set.json"
# DEV_PATH = "data/claim-evidence-set/dev_set.json"
TRAIN_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-train_set.json"
DEV_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-dev_set.json"

# Initialize BERT tokenizer and model for sequence classification
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=4)
model = model.to(DEVICE)

# Create data loaders
train_loader, dev_loader = create_dataloaders(TRAIN_PATH, DEV_PATH, tokenizer, batch_size=BATCH_SIZE, max_len=MAX_LEN)

# Define optimizer and learning rate scheduler
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

best_model_path = "/kaggle/working/baseline_bert_model_Autocast_explicitMarker_LR2e05.pt"

if __name__ == "__main__":
    start_time = time.time()
    train_model(model, train_loader, dev_loader, EPOCHS, optimizer, scheduler, best_model_path, autocast_flag=True)
    end_time = time.time()
    print("Model training time:", end_time-start_time)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


START TRAINING: 
----Epoch 1/10----
Training Loss: 1.0765
Confusion Matrix:
 [[66  0  2  0]
 [25  0  2  0]
 [ 9  0 32  0]
 [16  0  2  0]]
Validation Loss: {'avg_loss': 0.9402348279953003, 'accuracy': 0.6363636363636364, 'precision': 0.4754283828693992, 'recall': 0.6363636363636364, 'f1_score': 0.5324532374614928}
----Epoch 2/10----


KeyboardInterrupt: 

In [5]:
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW
import time

# Define hyperparameters
BATCH_SIZE = 16
EPOCHS = 10
MAX_LEN = 512
LEARNING_RATE = 5e-5

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Paths
# TRAIN_PATH = "data/claim-evidence-set/train_set.json"
# DEV_PATH = "data/claim-evidence-set/dev_set.json"
TRAIN_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-train_set.json"
DEV_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-dev_set.json"

# Initialize BERT tokenizer and model for sequence classification
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=4)
model = model.to(DEVICE)

# Create data loaders
train_loader, dev_loader = create_dataloaders(TRAIN_PATH, DEV_PATH, tokenizer, batch_size=BATCH_SIZE, max_len=MAX_LEN)

# Define optimizer and learning rate scheduler
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

best_model_path = "/kaggle/working/baseline_bert_model_Autocast_explicitMarker_LR5e05.pt"

if __name__ == "__main__":
    start_time = time.time()
    train_model(model, train_loader, dev_loader, EPOCHS, optimizer, scheduler, best_model_path, autocast_flag=True)
    end_time = time.time()
    print("Model training time:", end_time-start_time)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


START TRAINING: 
----Epoch 1/10----
Training Loss: 1.0765
Confusion Matrix:
 [[66  0  2  0]
 [25  0  2  0]
 [ 9  0 32  0]
 [16  0  2  0]]
Validation Loss: {'avg_loss': 0.9402348279953003, 'accuracy': 0.6363636363636364, 'precision': 0.4754283828693992, 'recall': 0.6363636363636364, 'f1_score': 0.5324532374614928}
----Epoch 2/10----


KeyboardInterrupt: 

In [5]:
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW
import time

# Define hyperparameters
BATCH_SIZE = 16
EPOCHS = 10
MAX_LEN = 512
LEARNING_RATE = 8e-5

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Paths
# TRAIN_PATH = "data/claim-evidence-set/train_set.json"
# DEV_PATH = "data/claim-evidence-set/dev_set.json"
TRAIN_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-train_set.json"
DEV_PATH = "/kaggle/input/claim-evidence-pair/claim-evidence-set/claim-evidence-dev_set.json"

# Initialize BERT tokenizer and model for sequence classification
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=4)
model = model.to(DEVICE)

# Create data loaders
train_loader, dev_loader = create_dataloaders(TRAIN_PATH, DEV_PATH, tokenizer, batch_size=BATCH_SIZE, max_len=MAX_LEN)

# Define optimizer and learning rate scheduler
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

best_model_path = "/kaggle/working/baseline_bert_model_Autocast_explicitMarker_LR8e05.pt"

if __name__ == "__main__":
    start_time = time.time()
    train_model(model, train_loader, dev_loader, EPOCHS, optimizer, scheduler, best_model_path, autocast_flag=True)
    end_time = time.time()
    print("Model training time:", end_time-start_time)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


START TRAINING: 
----Epoch 1/10----
Training Loss: 1.0765
Confusion Matrix:
 [[66  0  2  0]
 [25  0  2  0]
 [ 9  0 32  0]
 [16  0  2  0]]
Validation Loss: {'avg_loss': 0.9402348279953003, 'accuracy': 0.6363636363636364, 'precision': 0.4754283828693992, 'recall': 0.6363636363636364, 'f1_score': 0.5324532374614928}
----Epoch 2/10----


KeyboardInterrupt: 